let namae: string = "crushflix";
export function obito(n: string) {
  namae = n;
}
export let CONSTANTS = {
  name: namae,
  description:
    "<p><h1>Introducing CrushFlix - Your Ultimate Anime Sanctuary</h1><p>Are you tired of scouring the vast expanse of the internet for a safe and free anime streaming site? Look no further, because your search ends here at CrushFlix! Much like unraveling the mysteries in Death Note, you've finally discovered the missing piece to your anime collection puzzle.</p><h2>CrushFlix - Where Anime Dreams Come True</h2><p>Step into our anime haven, where every episode feels like a journey through the vivid landscapes of your favorite shows. Just like the immersive world of Sword Art Online, but without the fear of real-life consequences, CrushFlix welcomes you to a realm where anime dreams come true, all at no cost to you and with the highest regard for your safety.</p><h2>Endless Anime Delights, Without Interruption</h2><p>Imagine a streaming platform where you can dive into the action-packed scenes of Cowboy Bebop without any interruptions – no ads, no lag, and certainly no buffering. At CrushFlix, we offer a seamless streaming experience, ensuring that your anime adventures remain uninterrupted and thoroughly enjoyable.</p><p>A Treasure Trove of Titles, All Yours for Free</p><p>Is CrushFlix free? Absolutely! Delve into our vast library featuring thousands of anime titles, ranging from timeless classics like Neon Genesis Evangelion to the latest anime sensations. There are no strings attached, no sign-up required, and certainly no hidden fees – just pure anime bliss waiting to be explored.</p><h2>Safety and Legality Guaranteed</h2><p>Concerned about safety? Fear not! CrushFlix is fortified with robust security measures, akin to the impenetrable barrier spells in Blue Exorcist, ensuring your online safety at every turn. And rest assured, our platform operates within legal boundaries, providing you with a worry-free anime streaming experience.</p><p>So, why wait? Join us at CrushFlix, where the love for anime blooms and your next anime adventure awaits!</p>",
  short_description: "Introducing CrushFlix - Your Ultimate Anime Sanctuary",
};
